
        <main>
            <form action="agregar-prod" method="POST" class="my-4" id="formulario">
                <div class="row">
                    <!-- Marca del Producto -->
                    <div class="col-9">
                        <div class="form-group">
                            <label for="marca_producto">Marca del Producto</label>
                            <select required name="marca_producto" class="form-control" id="marca_producto">
                                <option value="">Seleccione una marca</option>
                                <?php
                                // Aquí generamos las opciones con las marcas pasadas como argumento
                                foreach ($marcas as $marca) {
                                    echo "<option value='{$marca->nombre}'>{$marca->nombre}</option>";
                                }
                                ?>
                            </select>
                        </div>
                    </div>

                    <!-- Tipo de Producto -->
                    <div class="col-9">
                        <div class="form-group">
                            <label for="tipo_producto">Tipo de Producto</label>
                            <input required name="tipo_producto" type="text" oninput="this.value = this.value.toUpperCase()" class="form-control" id="tipo_producto">
                        </div>
                    </div>

                    <!-- Modelo del Producto -->
                    <div class="col-9">
                        <div class="form-group">
                            <label for="modelo">Modelo del Producto</label>
                            <input required name="modelo" type="text" oninput="this.value = this.value.toUpperCase()" class="form-control" id="modelo">
                        </div>
                    </div>

                    <div class="col-9">
                        <div class="form-group">
                            <label>Precio</label>
                            <input required name="precio" type="number" class="form-control" id="precio">
                        </div>
                    </div>

                    <!-- Descripción del Producto -->
                    <div class="col-9">
                        <div class="form-group">
                            <label for="descripcion">Descripción del Producto</label>
                            <input required name="descripcion" type="text" oninput="this.value = this.value.toUpperCase()" class="form-control" id="descripcion">
                        </div>
                    </div>
                </div>

                <!-- Botón de Guardar -->
                <button type="submit" class="btn btn-primary mt-2" id="boton-guardar">Guardar</button>
            </form>
        </main>
        <?php

        ?>
        <ul class="list-group">
            <?php foreach ($productos as $producto) { ?>
                <li class="list-group-item marcas">
                    <div>
                        <b><?php echo "Marca: " . htmlspecialchars($producto->nombre_marca)  . " | " . "Categoria: " . htmlspecialchars ($producto->categoria) . " | ". "Modelo: " . htmlspecialchars ($producto->modelo) . " | " . "Precio: $" . htmlspecialchars($producto->precio); ?></b>
                    </div>
                    <div class="actions">
                        <a href="<?= BASE_URL ?>producto/<?php echo $producto->	ID_Productos ; ?>" type="button" class="btn btn-primary ml-auto">Ver Producto</a>
                        <a href="<?= BASE_URL ?>formModificar-producto/<?php echo $producto->ID_Productos ; ?>" type="button" class="btn btn-success ml-auto">Modificar</a>
                        <a href="<?= BASE_URL ?>eliminar-prod/<?php echo $producto->ID_Productos ; ?>" type="button" class="btn btn-danger ml-auto">Borrar</a>
                    </div>
                </li>
            <?php } ?>
        </ul>

   